name: CD production

on:
  push:
    tags-ignore:
      - 'v*-*'

jobs:
  deploy-frontend-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3.7.0
        id: docker-metadata
        with:
          images: ghcr.io/${{ github.repository }}/frontend

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: ./app
          file: ./dockerfiles/frontend-prod.Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          push: true
