name: Test

on:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          working-directory: app
